### PR TITLE
fix bytes encoding

### LINKED ISSUE #270: signTypedData() return value changed in 5.0.0
### Description

It appears that the output of `signTypedData()` has changed after I upgraded `@metamask/eth-sig-util` from `4.0.1` to `5.0.0`. Is it a bug? Or am I using the API incorrectly in some way?

### Steps to Reproduce

1. Clone [this repository](https://github.com/GitHubPang/MetaMask-eth-sig-util-issue-270).
	```bash
	git clone https://github.com/GitHubPang/MetaMask-eth-sig-util-issue-270
	cd MetaMask-eth-sig-util-issue-270/
	```

	As you can see, there are 2 folders, whose content is essentially the same except the version number of `@metamask/eth-sig-util`.

2. Run the script in each folder.
	```bash
	cd 4.0.1 && yarn install && yarn node run.js && cd ..
	```

	Output:

	```text
	yarn install v1.22.19
	warning package.json: No license field
	warning No license field
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	[3/4] Linking dependencies...
	[4/4] Building fresh packages...
	Done in 1.17s.
	yarn node v1.22.19
	warning package.json: No license field
	signature is 0x25172b7da83550708a406f11a8ebb50c22b0b53b86ff074b447166785d66e57a422c3184e03346bdda3c5a7f9861c96b642acdce831109d4b2a19c71b16bdc1b1b
	OK ✔
	Done in 0.23s.
	```
	
	----

	```bash
	cd 5.0.0 && yarn install && yarn node run.js && cd ..
	```

	Output:

	```text
	yarn install v1.22.19
	warning package.json: No license field
	warning No license field
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	[3/4] Linking dependencies...
	[4/4] Building fresh packages...
	Done in 0.27s.
	yarn node v1.22.19
	warning package.json: No license field
	signature is 0xbdeaf091701c02bbdb563849261378dd5f6b92bdcfe5ad996343786a9dd5946675b4d80320088ef812505f6d8ebefb18859e77a7f00d2fffd1757924e97cf9ac1b
	Wrong! 😲
	Done in 0.21s.
	```

### Expected Behaviour

They should give the same output.

### Actual Behaviour

In 5.0.0, `signTypedData()` returned a value that's different from that of 4.0.1.

### PR DESCRIPTION
**Pull request by ZumZoom**
fixes #270

### CODE REVIEW

File: src/sign-typed-data.ts [hunk 1]
```diff
@@ -174,7 +174,7 @@ function encodeField(
     if (typeof value === 'number') {
       value = numberToBuffer(value);
     } else if (isHexString(value)) {
-      value = numberToBuffer(parseInt(value, 16));
```
Comment (mcmire) [inline src/sign-typed-data.ts:177]: I believe (based on the comment in the [PR that changed this](https://github.com/MetaMask/eth-sig-util/commit/9f01c9d7922b717ddda3aa894c38fbba623e8bdf#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R128)) the change from `Buffer.from` to `numberToBuffer` was intentional, but I'm not sure why. @adonesky1 Would you be willing to elaborate on this?

Comment (adonesky1) [reply src/sign-typed-data.ts:177]: @mcmire this change was intentional. And apparently our testing was not sufficient to expose the regression here. This change was made in response to feedback provided [here](https://github.com/MetaMask/eth-sig-util/pull/260#pullrequestreview-1062614981) to a much larger set of changes in this suite of related functions. This change does seem to get us back on track. I am a bit concerned now however that there may be other regressions from [this PR ](https://github.com/MetaMask/eth-sig-util/pull/260)still lurking, since our test suite didn't catch this one...

Comment (adonesky1) [reply src/sign-typed-data.ts:177]: cc @kumavis

**Review by adonesky1 — APPROVED** [review]
